export const topSongs = [
  {
    top: 10,
    title: "Maple Syrup",
    artist: "The Backseat Lovers",
    img: "maple_syrup.jpg",
    link: "https://open.spotify.com/track/4MXE6VCvTsQitHWrAxj7Kg?si=1c8aacac9a7d4b51",
  },
  {
    top: 9,
    title: "I'm Just Snacking",
    artist: "Gus Dapperton",
    img: "im_just_snacking.jpg",
    link: "https://open.spotify.com/track/12jmugLskEWmYRLKYfMNSk?si=17b07eefcca941e6",
  },
  {
    top: 8,
    title: "This Is Why",
    artist: "Paramore",
    img: "this_is_why.jpg",
    link: "https://open.spotify.com/track/44bJrZ1ZTFKDIe3enEkYH7?si=b9805b65165840b9",
  },
  {
    top: 7,
    title: "Scrawny",
    artist: "Wallows",
    img: "scrawny.png",
    link: "https://open.spotify.com/track/1pNUmVxDiE8t6P1XxcZAv8?si=4a93dd34d4314221",
  },
  {
    top: 6,
    title: "Fly As Me",
    artist: "Bruno Mars",
    img: "fly_as_me.jpg",
    link: "https://open.spotify.com/track/7suB6D6uKX5DfPukdGaz0W?si=05f502063c9741a9",
  },
  {
    top: 5,
    title: "Dark Red",
    artist: "Steve Lacy",
    img: "dark_red.jpg",
    link: "https://open.spotify.com/track/3EaJDYHA0KnX88JvDhL9oa?si=7cb275cc51b342ff",
  },
  {
    top: 4,
    title: "Matilda",
    artist: "Harry Styles",
    img: "matilda.jpeg",
    link: "https://open.spotify.com/track/6uvh0In7u1Xn4HgxOfAn8O?si=0902ea4ff5ab4a74",
  },
  {
    top: 3,
    title: "Sweet Marie",
    artist: "The Walters",
    img: "sweet_marie.jpg",
    link: "https://open.spotify.com/track/7MBSbBrx0TvBYyKEcpGcJb?si=a0b6fd29c2f148d1",
  },
  {
    top: 2,
    title: "Hello Anxiety",
    artist: "Phum Viphurit",
    img: "hello_anxiety.jpg",
    link: "https://open.spotify.com/track/1ZseaIKt19broBzze3F8hz?si=bc782858a011476f",
  },
  {
    top: 1,
    title: "Fallen",
    artist: "Lola Amour",
    img: "fallen.jpg",
    link: "https://open.spotify.com/track/4mc3rUoMwwiNTHA4al9nNd?si=4b3a88951cc34fcb",
  },
];
